# Generated by Django 3.1.2 on 2020-12-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diabitic',
            fields=[
                ('Patient_ID', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('Gender', models.IntegerField()),
                ('Blood_Pressure', models.IntegerField()),
                ('Pregnancies', models.IntegerField()),
                ('SkinThickness', models.CharField(max_length=5)),
                ('Insulin', models.CharField(max_length=5)),
                ('Glucose', models.CharField(max_length=5)),
                ('BMI', models.CharField(max_length=5)),
                ('Age', models.CharField(max_length=5)),
                ('Result', models.CharField(max_length=1)),
            ],
        ),
    ]
